package view.claire;

import java.awt.event.*;
import javax.swing.*;
import java.awt.*;

/**
	The NavigationListener is an Action Listener class used by any buttons in the GUI that cause a new menu or screen to be loaded
	into the GUI window of the application. 
	@author Claire Campbell
*/
public class NavigationListener implements ActionListener 
{
	/**
		The actionPerformed() method of NavigationListener calls the MainView's loadMenu() method in order
			to load a menu or GUI panel into the window of the application. The method is executed whenever
			the user clicks a GUI button that causes the application to switch to a new menu or GUI screen.
		@param ae The ActionEvent generated by the component clicked on by the user.
	*/
	public void actionPerformed(ActionEvent ae)
	{
		JButton source = (JButton)ae.getSource();
		MainView parent = (MainView)SwingUtilities.getWindowAncestor(source);
		parent.loadMenu(ae.getActionCommand());
	}
}